### ISSUE TITLE
quiero hacer un issue #10 porque jodida se nace.

### ISSUE THREAD

**Issue by jpalandri** [pignacio/vld_django#10]
y además mandarle un saludo a todos los que me conocen. y que el + de la página de días te pueda agregar efectivamente un día, que me rompe las pelotas tener que entrar a un día ya usado. besis.

**Comment by pignacio** [comment]
Con que te muestre el día de hoy en la lista alcanza?

Los agujeros de días vacíos entre los que no llenaste ya los está
completando.

i.e: con que aparezcan todos los dias menores o iguales a hoy estamos, no?

En cualquier caso tmb hay que arreglar el bug :P

**Comment by jpalandri** [comment]
no entendí nada de lo que pusiste salvo hay que arreglar el bug.

2015-05-28 12:25 GMT+02:00 Ignacio Rossi notifications@github.com:

> Con que te muestre el día de hoy en la lista alcanza?
> 
> Los agujeros de días vacíos entre los que no llenaste ya los está
> completando.
> 
> i.e: con que aparezcan todos los dias menores o iguales a hoy estamos, no?
> 
> En cualquier caso tmb hay que arreglar el bug :P
> 
> El 28 de mayo de 2015, 6:53, jpalandri notifications@github.com
> escribió:
> 
> > y además mandarle un saludo a todos los que me conocen. y que el + de la
> > página de días te pueda agregar efectivamente un día, que me rompe las
> > pelotas tener que entrar a un día ya usado. besis.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/pignacio/vld_django/issues/10.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pignacio/vld_django/issues/10#issuecomment-106264143.

## 

Juli

"Be yourself; everyone else is already taken."
— Oscar Wilde

**Comment by pignacio** [comment]
Suponete que entras a la lista de comidas y aunque no hayas llenado nada,
el dia de hoy aparece (vacio).
Entonces no tendrías qe usar mas el +, no?

**Comment by jpalandri** [comment]
es lo mismo. click en el dia ya creado pero vacío, o click en el + para que
se cree, me da igual.

2015-05-28 12:48 GMT+02:00 Ignacio Rossi notifications@github.com:

> Suponete que entras a la lista de comidas y aunque no hayas llenado nada,
> el dia de hoy aparece (vacio).
> Entonces no tendrías qe usar mas el +, no?
> 
> El 28 de mayo de 2015, 7:31, jpalandri notifications@github.com
> escribió:
> 
> > no entendí nada de lo que pusiste salvo hay que arreglar el bug.
> > 
> > 2015-05-28 12:25 GMT+02:00 Ignacio Rossi notifications@github.com:
> > 
> > > Con que te muestre el día de hoy en la lista alcanza?
> > > 
> > > Los agujeros de días vacíos entre los que no llenaste ya los está
> > > completando.
> > > 
> > > i.e: con que aparezcan todos los dias menores o iguales a hoy estamos,
> > > no?
> > > 
> > > En cualquier caso tmb hay que arreglar el bug :P
> > > 
> > > El 28 de mayo de 2015, 6:53, jpalandri notifications@github.com
> > > escribió:
> > > 
> > > > y además mandarle un saludo a todos los que me conocen. y que el + de
> > > > la
> > > > página de días te pueda agregar efectivamente un día, que me rompe
> > > > las
> > > > pelotas tener que entrar a un día ya usado. besis.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/pignacio/vld_django/issues/10.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/pignacio/vld_django/issues/10#issuecomment-106264143
> > > .
> > 
> > ## 
> > 
> > Juli
> > 
> > "Be yourself; everyone else is already taken."
> > — Oscar Wilde
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/pignacio/vld_django/issues/10#issuecomment-106265287
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pignacio/vld_django/issues/10#issuecomment-106269767.

## 

Juli

"Be yourself; everyone else is already taken."
— Oscar Wilde

**Comment by pignacio** [comment]
Lo partí en #11 y #12

**Comment by pignacio** [comment]
Hoy después de tus 12 (preferentemente) o mañana chequeá si el dia te
aparece en la lista sin que lo agregues a mano :)

Si está todo bien, podes cerrar esto despues de eso :)

**Comment by jpalandri** [comment]
Bueno. Vendido al señor de la pelada. Lo cerramos.
