### ISSUE TITLE
quiero nuevos colores para la tabla de comidas. yo te los busco.

### ISSUE THREAD

**Issue by jpalandri** [pignacio/vld_django#9]
besis de colores (?) #ositoscariñosos :rainbow:

**Comment by jpalandri** [comment]
btw, el theme que me pasaste tenía esquema de colores para las tablas. ese no sirve? o es el que hay ahora? (no creo, no lo vi tan verde, pero me puedo haber equivocado)

**Comment by pignacio** [comment]
Te animas a hacer el pull request? :) :O :blush:

**Comment by pignacio** [comment]
El theme tiene colores contextuales (para marcar una fila con "danger", ponele), podemos usar esos, pero me suena que van a quedar fieros :O

https://bootswatch.com/superhero/#tables

**Comment by jpalandri** [comment]
fiajte qué onda:

para editar comida:

day total: el verde
total parcial: el naranja
contenidos: el grisesito

y la otra fijate si algo similar sirve. :D

2015-05-30 16:34 GMT+02:00 Ignacio Rossi notifications@github.com:

> El theme tiene colores contextuales (para marcar una fila con "danger",
> ponele), podemos usar esos, pero me suena que van a quedar fieros :O
> 
> https://bootswatch.com/superhero/#tables
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pignacio/vld_django/issues/9#issuecomment-107045584.

## 

Juli

"Be yourself; everyone else is already taken."
— Oscar Wilde
